version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.15
    - 7.13.8
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.24.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.5
    - 7.13.8
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.133
